"""Deterministic control-intent router for the Qwen Voice PE bridge.

WHY THIS EXISTS
---------------
Qwen-Omni-Realtime has **no** ``tool_choice`` or ``parallel_tool_calls``
parameter (confirmed in the official Alibaba Cloud docs).  The model therefore
*probabilistically* decides whether to call Home Assistant tools, and was
observed live answering ``好的，正在打开卧室的灯`` while emitting
``tool_called=False`` — a verbal false-success with no action underneath.

This module removes that nondeterminism for high-confidence control
utterances.  A local, rule-based router reads the final ASR transcript,
resolves the exact entity/tool/arguments against a catalog of *exposed* Home
Assistant entities, and returns a concrete tool call for the bridge to execute
deterministically.  Ambiguous utterances return ``None`` so the model keeps its
normal free-form behaviour.
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass
from typing import Optional
from urllib import request

logger = logging.getLogger(__name__)


# Domains that participate in control routing.  Sensor/binary_sensor/todo are
# deliberately excluded: they are read-only and are handled by the model via
# GetLiveContext without forcing.
CONTROL_DOMAINS = {
    "light",
    "switch",
    "cover",
    "fan",
    "climate",
    "media_player",
}

# Domain -> Chinese keyword hints the user is likely to say.  Used only as a
# disambiguation hint, never as the sole source of truth (the entity name token
# match is what actually selects an entity).
DOMAIN_KEYWORDS = {
    "light": ("灯", "灯光", "吸顶灯", "照明", "亮度"),
    "climate": ("空调", "冷气", "暖气", "温度"),
    "fan": ("净化器", "风扇", "空气净化"),
    "cover": ("晾衣", "晾衣机", "晾衣架", "升降"),
    "media_player": ("电视", "音箱", "音响", "音量", "华为", "xbox", "appletv", "wowei"),
    "switch": ("开关", "电源"),
}


@dataclass(frozen=True)
class EntityInfo:
    name: str
    domain: str
    area: str = ""
    device_class: str = ""
    entity_id: str = ""
    state: str = ""

    def keywords(self) -> list[str]:
        """Tokenise a friendly name into matchable keywords."""
        tokens = re.findall(r"[\u4e00-\u9fff]+|[A-Za-z0-9]+", self.name)
        return [t.lower() for t in tokens if len(t) >= 2]


@dataclass(frozen=True)
class Intent:
    tool: str
    arguments: dict
    entity: EntityInfo
    description: str  # short Chinese description used for the confirmation note


@dataclass(frozen=True)
class RouterRule:
    """Dynamic forced-routing rule generated from an auto-discovered tool.

    Capability tools generated by ``ha_tool_builder`` carry a rule so the
    harness deterministically routes common intents (空调模式/风速/摆风、净化器
    预设) to the right tool, instead of leaving them to the model's guess.
    """

    tool: str
    param: str
    domain: str
    keywords: tuple
    value_map: dict


def _to_simplified(text: str) -> str:
    """Map the handful of traditional area names present in this home to
    simplified Chinese so a user saying ``客厅`` still matches an area ``客廳``."""
    return (
        text.replace("客廳", "客厅")
        .replace("臥室", "卧室")
        .replace("廚房", "厨房")
        .replace("衛浴", "卫浴")
        .replace("陽台", "阳台")
    )


def _parse_number(text: str, maximum: int = 100) -> Optional[int]:
    m = re.search(r"(\d{1,3})(?:\s*[%％])?", text)
    if not m:
        return None
    return max(0, min(maximum, int(m.group(1))))


_CN_DIGITS = {
    "零": 0, "一": 1, "二": 2, "两": 2, "三": 3, "四": 4,
    "五": 5, "六": 6, "七": 7, "八": 8, "九": 9,
}


def _parse_chinese_number(text: str) -> Optional[int]:
    """Parse a Chinese numeral (0-99), e.g. 二十四 -> 24, 五十 -> 50."""
    # "一点" (a little) means "a bit", not the numeral 1; strip it so a
    # relative command like "调暗一点" does not resolve to brightness 1.
    candidate = text.replace("一点", "")
    m = re.search(r"[零一二两三四五六七八九十]{1,4}", candidate)
    if not m:
        return None
    token = m.group(0)
    if "十" in token:
        left, _, right = token.partition("十")
        tens = _CN_DIGITS.get(left, 1) if left else 1
        ones = _CN_DIGITS.get(right, 0) if right else 0
        return tens * 10 + ones
    if len(token) == 1 and token in _CN_DIGITS:
        return _CN_DIGITS[token]
    return None


def _parse_control_number(text: str, maximum: int = 100) -> Optional[int]:
    """Parse either an Arabic or a Chinese numeral for a control quantity."""
    number = _parse_number(text, maximum)
    if number is not None:
        return number
    number = _parse_chinese_number(text)
    if number is None:
        return None
    return max(0, min(maximum, number))


class EntityCatalog:
    """Catalog of exposed Home Assistant entities, resolved by Chinese name."""

    def __init__(self, entities: Optional[list[EntityInfo]] = None):
        self.entities: list[EntityInfo] = list(entities or [])

    def by_name(self, name: str) -> Optional[EntityInfo]:
        for entity in self.entities:
            if entity.name == name:
                return entity
        return None

    def resolve(self, text: str, domain_hint: Optional[str] = None) -> Optional[EntityInfo]:
        """Pick the most likely controllable entity for an utterance."""
        best: Optional[EntityInfo] = None
        best_score = 0
        second_score = 0
        norm = _to_simplified(text).lower()
        hint = domain_hint or self.domain_hint_from_text(text)
        for entity in self.entities:
            if entity.domain not in CONTROL_DOMAINS:
                continue
            if hint and entity.domain != hint:
                continue
            score = self._match_score(norm, entity)
            if score > best_score:
                second_score = best_score
                best, best_score = entity, score
            elif score > second_score:
                second_score = score
        # Only act when there is a strict winner.  A tie between two entities
        # (e.g. two lights both in the mentioned area) is genuinely ambiguous:
        # guessing can turn off the wrong device, so defer to the model / a
        # clarification instead.
        if best_score > 0 and best_score > second_score:
            return best
        # Fall back to a *unique* entity in the hinted domain.  Most homes have
        # exactly one light / climate / fan / cover, so a bare "开灯" /
        # "开空调" maps correctly without the user spelling the full name.
        if hint:
            same = [
                e for e in self.entities
                if e.domain == hint and e.domain in CONTROL_DOMAINS
            ]
            if len(same) == 1:
                # Safety: if the user explicitly mentioned an area that does
                # NOT match the only candidate, do not guess — let the model
                # ask for clarification (a "开客厅的空调" with only a bedroom
                # climate must not silently target the bedroom unit).
                mentioned = self._mentioned_areas(norm)
                area = _to_simplified(same[0].area)
                if mentioned and area not in mentioned:
                    logger.info(
                        "Domain %s has one candidate (%s) but user mentioned area(s) %s; deferring to model",
                        hint, same[0].name, sorted(mentioned),
                    )
                    return None
                return same[0]
        return None

    def _mentioned_areas(self, norm_text: str) -> set:
        """Areas (simplified) explicitly mentioned in the utterance."""
        mentioned: set = set()
        for entity in self.entities:
            area = _to_simplified(entity.area)
            if area and area in norm_text:
                mentioned.add(area)
        return mentioned

    def domain_hint_from_text(self, text: str) -> Optional[str]:
        norm = _to_simplified(text).lower()
        # Longer, more specific keywords are checked first so "空气净化器"
        # resolves to fan rather than a shorter overlapping token.
        ordered = sorted(
            DOMAIN_KEYWORDS.items(),
            key=lambda kv: -max(len(k) for k in kv[1]),
        )
        for domain, keywords in ordered:
            for keyword in keywords:
                if keyword.lower() in norm:
                    return domain
        return None

    @staticmethod
    def _match_score(norm_text: str, entity: EntityInfo) -> int:
        score = 0
        name = _to_simplified(entity.name).lower()
        # Exact full-name match (strongest signal).
        if name and name in norm_text:
            score += 5
        # CJK sub-string overlap: "关客厅的灯" contains "客厅" which appears in
        # "客厅吊灯"; "关卧室的灯" contains "卧室" which appears in "卧室吸顶灯".
        # This lets a room word baked into the friendly name win over a mere
        # area-assignment tie.
        cjk = "".join(re.findall(r"[\u4e00-\u9fff]+", norm_text))
        seen: set = set()
        for start in range(len(cjk)):
            for size in (3, 2):
                end = start + size
                if end > len(cjk):
                    continue
                chunk = cjk[start:end]
                if chunk in seen:
                    continue
                seen.add(chunk)
                if chunk in name:
                    score += 2
        # Entity is assigned to the area the user mentioned.
        if entity.area and _to_simplified(entity.area) in norm_text:
            score += 2
            # The entity's own name carries that area word -> decisive local
            # signal ("客厅吊灯" vs "关客厅的灯").
            if _to_simplified(entity.area) in name:
                score += 3
        return score

    # --- builders ---------------------------------------------------------

    @classmethod
    def from_live_context_text(cls, text: str) -> "EntityCatalog":
        """Parse ha-mcp ``GetLiveContext`` output into a catalog."""
        entities: list[EntityInfo] = []
        current: Optional[dict] = None
        in_attributes = False
        for raw_line in text.splitlines():
            line = raw_line.rstrip()
            if not line.strip():
                continue
            if line.startswith("- names:"):
                if current and current.get("name"):
                    entities.append(cls._dict_to_entity(current))
                current = {"name": line.split(":", 1)[1].strip()}
                in_attributes = False
                continue
            if current is None:
                continue
            stripped = line.strip()
            if stripped.startswith("attributes:"):
                in_attributes = True
                continue
            if stripped.startswith("domain:"):
                current["domain"] = stripped.split(":", 1)[1].strip()
            elif stripped.startswith("state:"):
                current["state"] = stripped.split(":", 1)[1].strip().strip("'\"")
            elif stripped.startswith("areas:"):
                current["area"] = stripped.split(":", 1)[1].strip()
            elif in_attributes and stripped.startswith("device_class:"):
                current["device_class"] = stripped.split(":", 1)[1].strip()
        if current and current.get("name"):
            entities.append(cls._dict_to_entity(current))
        return cls(entities)

    @staticmethod
    def _dict_to_entity(data: dict) -> EntityInfo:
        return EntityInfo(
            name=data.get("name", ""),
            domain=data.get("domain", ""),
            area=data.get("area", ""),
            device_class=data.get("device_class", ""),
            state=data.get("state", ""),
        )


class ControlIntentRouter:
    """Rule-based detector that turns a transcript into a forced tool call."""

    # Ordered by priority.  Each tuple: (tool, verb keywords).
    TURN_ON_TOOL = "HassTurnOn"
    TURN_OFF_TOOL = "HassTurnOff"
    LIGHT_SET_TOOL = "HassLightSet"
    CLIMATE_SET_TOOL = "HassClimateSetTemperature"
    FAN_SET_TOOL = "HassFanSetSpeed"
    COVER_STOP_TOOL = "HassStopMoving"

    # Sub-function switches: spoken word -> token found in the switch's
    # friendly name.  Used to route "打开净化器童锁" to the child-lock switch
    # instead of the parent device.  Add entries as more sub-function switches
    # are exposed to Assist.
    SUB_FUNCTION_ALIASES = {
        "童锁": "child lock",
        "杀菌": "uv sterilization",
    }

    ON_VERBS = ("打开", "开启", "启动", "开一下", "点亮")
    OFF_VERBS = ("关闭", "关掉", "关一下", "熄灭", "关上")

    # Single-character forms are accepted only when an entity/domain resolves,
    # so stray "开"/"关" inside unrelated words never trigger a forced action.
    ON_CHARS = ("开",)
    OFF_CHARS = ("关",)

    def __init__(
        self,
        catalog: EntityCatalog,
        dynamic_rules: Optional[list[RouterRule]] = None,
    ):
        self.catalog = catalog
        self.dynamic_rules: list[RouterRule] = list(dynamic_rules or [])

    def register_dynamic_rules(self, rules):
        """Register forced-routing rules for auto-generated capability tools."""
        for rule in rules:
            if rule is not None:
                self.dynamic_rules.append(rule)

    def resolve(self, transcript: str) -> Optional[Intent]:
        text = (transcript or "").strip()
        if not text:
            return None
        norm = _to_simplified(text)

        # 0) Dynamic forced-routing rules from auto-generated capability tools
        # (空调模式/风速/摆风、净化器预设).  The rule's domain must be hinted in
        # the utterance AND one of its value keywords must appear, so a bare
        # "自动" alone never fires a forced action.
        for rule in self.dynamic_rules:
            entity = self._resolve_entity_if_hinted(text, rule.domain)
            if entity is None:
                continue
            value = self._detect_value(norm, rule.value_map)
            if value is None:
                continue
            return Intent(
                tool=rule.tool,
                arguments={"name": entity.name, rule.param: value},
                entity=entity,
                description=f"把{entity.name}设置为{value}",
            )

        # 1) brightness for lights
        light_entity = self._resolve_entity_if_hinted(text, "light")
        if light_entity is not None and (
            self._has_any(norm, ("亮度", "调亮", "调暗", "亮一点", "暗一点", "最暗", "最亮"))
            or (self._has_any(norm, ("调", "调到", "百分之")) and _parse_control_number(text) is not None)
        ):
            brightness = _parse_control_number(text)
            if brightness is None:
                if "最暗" in norm:
                    brightness = 1
                elif "最亮" in norm:
                    brightness = 100
                else:
                    brightness = 80 if self._has_any(norm, ("调亮", "亮一点")) else 30
            return Intent(
                tool=self.LIGHT_SET_TOOL,
                arguments={"name": light_entity.name, "domain": ["light"], "brightness": brightness},
                entity=light_entity,
                description=f"把{light_entity.name}亮度设为{brightness}%",
            )

        # 2) temperature for climate
        climate_entity = self._resolve_entity_if_hinted(text, "climate")
        if climate_entity and self._has_any(norm, ("温度", "调到", "度")):
            temperature = _parse_control_number(text, maximum=35)
            if temperature is not None and temperature >= 16:
                return Intent(
                    tool=self.CLIMATE_SET_TOOL,
                    arguments={"name": climate_entity.name, "temperature": temperature},
                    entity=climate_entity,
                    description=f"把{climate_entity.name}温度设为{temperature}度",
                )

        # 3) fan speed
        fan_entity = self._resolve_entity_if_hinted(text, "fan")
        if fan_entity and self._has_any(norm, ("风速", "档", "风量")):
            percentage = _parse_control_number(text)
            if percentage is None:
                percentage = 30 if self._has_any(norm, ("低", "小")) else (80 if self._has_any(norm, ("高", "大")) else 50)
            return Intent(
                tool=self.FAN_SET_TOOL,
                arguments={"name": fan_entity.name, "domain": ["fan"], "percentage": percentage},
                entity=fan_entity,
                description=f"把{fan_entity.name}风速设为{percentage}%",
                )

        # 3c) cover motion (晾衣架/晾衣机 上升/下降/停止).  The AUPU drying rack
        # is a *stateless* cover: open_action sends the 433 MHz RF up code,
        # close_action sends down, stop_action sends stop.  So route to
        # HassTurnOn/HassTurnOff/HassStopMoving, NOT HassSetPosition (the rack
        # has no position state).
        cover_entity = self._resolve_entity_if_hinted(text, "cover")
        if cover_entity:
            motion = self._detect_cover_motion(norm)
            if motion == "up":
                return Intent(
                    tool=self.TURN_ON_TOOL,
                    arguments={"name": cover_entity.name, "domain": ["cover"]},
                    entity=cover_entity,
                    description=f"上升{cover_entity.name}",
                )
            if motion == "down":
                return Intent(
                    tool=self.TURN_OFF_TOOL,
                    arguments={"name": cover_entity.name, "domain": ["cover"]},
                    entity=cover_entity,
                    description=f"下降{cover_entity.name}",
                )
            if motion == "stop":
                return Intent(
                    tool=self.COVER_STOP_TOOL,
                    arguments={"name": cover_entity.name, "domain": ["cover"]},
                    entity=cover_entity,
                    description=f"停止{cover_entity.name}",
                )

        # 4) on / off (most common)
        is_on = self._has_any(norm, self.ON_VERBS)
        is_off = self._has_any(norm, self.OFF_VERBS)
        if not is_on and not is_off:
            is_on = any(ch in norm for ch in self.ON_CHARS)
            is_off = any(ch in norm for ch in self.OFF_CHARS)
        if is_on == is_off:
            # both or neither -> not a confident on/off command
            return None
        # Sub-function switch (童锁/杀菌…) wins over the parent device: opening
        # the child lock must target the switch, not the purifier fan itself.
        sub_switch = self._sub_function_switch(norm, "")
        entity = None
        if sub_switch is None:
            entity = self.catalog.resolve(text)
            if entity is not None:
                sub_switch = self._sub_function_switch(norm, entity.name)
                entity = sub_switch or entity
        else:
            entity = sub_switch
        if entity is None:
            return None
        if is_on:
            return Intent(
                tool=self.TURN_ON_TOOL,
                arguments={"name": entity.name, "domain": [entity.domain]},
                entity=entity,
                description=f"打开{entity.name}",
            )
        return Intent(
            tool=self.TURN_OFF_TOOL,
            arguments={"name": entity.name, "domain": [entity.domain]},
            entity=entity,
            description=f"关闭{entity.name}",
        )

    def _resolve_entity_if_hinted(self, text: str, domain: str) -> Optional[EntityInfo]:
        """Resolve an entity only when the domain is actually hinted in the text.

        Prevents a bare "调到26度" from matching a climate entity out of the
        blue, while still allowing "把空调调到26度" to select the single
        climate device.
        """
        if self.catalog.domain_hint_from_text(text) != domain:
            return None
        return self.catalog.resolve(text, domain)

    @staticmethod
    def _has_any(text: str, keywords) -> bool:
        return any(k in text for k in keywords)

    @staticmethod
    def _detect_value(text: str, mapping: dict) -> Optional[str]:
        """Return the first mapped HA value whose Chinese keyword is in text."""
        for keyword, value in mapping.items():
            if keyword in text:
                return value
        return None

    def _sub_function_switch(self, norm_text: str, parent_name: str) -> Optional[EntityInfo]:
        """Find a switch whose friendly name matches <parent> + alias token."""
        for cn_word, en_token in self.SUB_FUNCTION_ALIASES.items():
            if cn_word not in norm_text:
                continue
            matches = []
            for entity in self.catalog.entities:
                if entity.domain != "switch":
                    continue
                name = entity.name
                # Match either the Chinese word (switch renamed to 童锁) or the
                # English token (switch named "...Child lock").
                if cn_word in name or en_token in name.lower():
                    matches.append(entity)
            if not matches:
                continue
            if parent_name:
                for entity in matches:
                    if parent_name in entity.name:
                        return entity
            if len(matches) == 1:
                return matches[0]
            # Ambiguous: prefer the first exposed switch with the alias.
            return matches[0]
        return None

    @staticmethod
    def _detect_cover_motion(norm_text: str) -> Optional[str]:
        text = norm_text.lower()
        if ControlIntentRouter._has_any(text, ("停止", "停下", "停一下", "stop")):
            return "stop"
        if ControlIntentRouter._has_any(
            text, ("上升", "升起", "抬高", "升到顶", "升上去", "升起来", "升一点", "升")
        ):
            return "up"
        if ControlIntentRouter._has_any(
            text, ("下降", "降下", "放低", "降到最低", "降下来", "降下去", "降一点", "降")
        ):
            return "down"
        return None


def build_catalog_from_ha(
    mcp_url: str,
    access_token: str,
    *,
    timeout: float = 20.0,
    retries: int = 5,
    retry_delay: float = 3.0,
) -> EntityCatalog:
    """Build an entity catalog from Home Assistant at startup.

    Uses the MCP ``GetLiveContext`` tool so the catalog reflects exactly the
    *exposed* entities the MCP/Assist layer can act on (including area names).
    Retries briefly because, right after a host/HAOS reboot, the add-on can
    start before Home Assistant Core and its MCP endpoint are fully ready; a
    single failed attempt would otherwise leave deterministic routing disabled
    until the add-on is manually restarted.  On final failure it falls back to
    an empty catalog — routing simply stays disabled and the model behaves as
    before.
    """
    last_error = "unknown"
    for attempt in range(1, max(1, retries) + 1):
        try:
            text = _call_mcp_tool(mcp_url, access_token, "GetLiveContext", {}, timeout)
            if text:
                parsed = _extract_live_context_result(text)
                catalog = EntityCatalog.from_live_context_text(parsed)
                if catalog.entities:
                    logger.info(
                        "Entity catalog built: %u exposed entities "
                        "(%u controllable) on attempt %d",
                        len(catalog.entities),
                        sum(1 for e in catalog.entities if e.domain in CONTROL_DOMAINS),
                        attempt,
                    )
                    return catalog
            last_error = "empty GetLiveContext result"
        except Exception as e:  # noqa: BLE001 - we retry, then degrade safely
            last_error = repr(e)
            logger.warning(
                "Entity catalog build attempt %d/%d failed: %s",
                attempt, retries, e,
            )
        if attempt < retries:
            time.sleep(retry_delay)
    logger.warning(
        "Entity catalog is empty after %d attempt(s) (%s); deterministic control routing disabled",
        retries, last_error,
    )
    return EntityCatalog()


def _extract_live_context_result(mcp_output: str) -> str:
    """The HA MCP tool result is itself a JSON string containing ``result``."""
    try:
        data = json.loads(mcp_output)
        if isinstance(data, dict) and data.get("result"):
            return str(data["result"])
    except (json.JSONDecodeError, TypeError):
        pass
    return mcp_output


def _call_mcp_tool(
    mcp_url: str,
    access_token: str,
    tool_name: str,
    arguments: dict,
    timeout: float,
) -> str:
    """Minimal stateless Streamable-HTTP MCP call using only the stdlib."""
    payload = json.dumps(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": tool_name, "arguments": arguments},
        }
    ).encode("utf-8")
    req = request.Request(
        mcp_url,
        data=payload,
        method="POST",
        headers={
            "Content-Type": "application/json",
            "Accept": "application/json, text/event-stream",
            "Authorization": f"Bearer {access_token}",
        },
    )
    with request.urlopen(req, timeout=timeout) as resp:
        body = resp.read().decode("utf-8")
    data = json.loads(body)
    content = (data.get("result") or {}).get("content") or []
    parts = []
    for item in content:
        if isinstance(item, dict) and item.get("type") == "text":
            parts.append(item.get("text", ""))
    return "".join(parts)
