"""Small provider contract; no assumption that a provider needs a WebSocket."""

from dataclasses import dataclass, field
from typing import AsyncIterator, Protocol, runtime_checkable

from app.core.events import AudioChunk, CanonicalEvent, EventScope
from app.tools.schema import CanonicalTool, CanonicalToolResult


@dataclass(frozen=True)
class ProviderSession:
    instructions: str = field(repr=False)
    tools: tuple[CanonicalTool, ...] = ()
    max_output_tokens: int | None = None


@runtime_checkable
class RealtimeProvider(Protocol):
    @property
    def automatic_responses(self) -> bool: ...
    async def connect(self, scope: EventScope) -> None: ...
    async def disconnect(self) -> None: ...
    async def configure_session(self, session: ProviderSession) -> None: ...
    def begin_turn(self, scope: EventScope) -> None: ...
    async def send_audio(self, audio: AudioChunk) -> None: ...
    async def commit_audio(self) -> None: ...
    async def clear_input_audio(self) -> None: ...
    async def create_response(self, scope: EventScope) -> None: ...
    async def cancel_response(self) -> None: ...
    async def send_tool_result(self, call_id: str, result: CanonicalToolResult) -> None: ...
    async def provide_execution_context(self, result: CanonicalToolResult) -> None: ...
    async def update_tools(self, tools: tuple[CanonicalTool, ...]) -> None: ...
    async def update_instructions(self, instructions: str) -> None: ...
    def receive_events(self) -> AsyncIterator[CanonicalEvent]: ...
